require("Yro.Native.Remap")
require("Yro.Native.Set")

require("Yro.Plugins.Packer")

require("Yro.Plugins.Autopairs")
require("Yro.Plugins.Colorizer")
require("Yro.Plugins.DAP")
require("Yro.Plugins.Harpoon")
require("Yro.Plugins.Lazygit")
require("Yro.Plugins.LSP")
require("Yro.Plugins.Regexplainer")
require("Yro.Plugins.Treesitter")
require("Yro.Plugins.Telescope")
require("Yro.Plugins.Undotree")
